stages:
- verify
- deploy

image: maven:3.3.9-jdk-8

cache:
  paths:
    - .m2/repository

.verify: &verify
  stage: verify
  script:
    - 'mvn $MAVEN_CLI_OPTS install'
  artifacts:
    paths:
      - target/vBungee.jar
  cache:
    paths:
      - target/vBungee.jar

# Verify merge requests using JDK8
verify:jdk8:
  <<: *verify

upload:
  stage: deploy
  image: debian
  script:
    - 'apt-get update -y'
    - 'apt-get install lftp curl -y'
    - 'lftp -c "set sftp:auto-confirm yes ; open -u $ftp_username,$ftp_password sftp://$ftp_host ; put -O plugins/ target/vBungee.jar ; quit"'
    - 'curl "https://panel.benh.codes/api/client/servers/d66387f9/command" -H "Authorization: Bearer $pterodactyl_api_key" -H "Content-Type: application/json" -H "Accept: Application/vnd.pterodactyl.v1+json" -X POST -d "{ \"command\": \"grestart 5m Network Maintenance\" }"'
  only:
    - tags