Database:
  Host: ''
  Port: '3306'
  Database: ''
  Username: ''
  Password: ''
  Params: '&useSSL=false'
Lobbies:
  - Lobby1
Discord:
  Enabled: true
  Prefix: 'v!'
  Permissions:
    AddProof: 'vSuite Developers'
    Link: 'everyone'
  Ids:
    Guild: '700059392770441216'
    Punishments: '701014077266198581'
    Verified: '701553710383366234'
  RoleSync:
    vSuiteDev: '700059631430664253'
  Token: ''
WebAPI:
  Enabled: true
  Port: 6544
  Secret: ''