Database:
  Host: ''
  Port: '3306'
  Database: ''
  Username: ''
  Password: ''
  Params: '&useSSL=false'
Lobbies:
  - Lobby1
Discord:
  Enabled: true
  Prefix: 'v!'
  Permissions:
    AddProof: 'vSuite Developers'
  Ids:
    Guild: '700059392770441216'
    Punishments: '701014077266198581'
  Token: 'NzAxMDEyNTYwMTI3ODUyNTc1.XprS3A.51maPJOgaIdEMiu-n7Fyn2jqavM'