workflows:
  version: 2
  build_deploy:
    jobs:
      - setup-environment
      - build:
          requires:
            - setup-environment
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps: # a collection of steps
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: vBungee-{{ checksum "pom.xml" }}
      - run: 
          name: Download Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: vBungee-{{ checksum "pom.xml" }}
      - run: 
          name: Build Project
          command: mvn install
      - store_artifacts: 
          path: target/vBungee.jar
  deploy:
    docker:
      - image: debian
    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt-get update;
            sudo apt-get install lftp;
      - run:
          name: Deploy to Bungee
          command: |
            lftp -c "set sftp:auto-confirm yes ; open -u ${ftp_username},${ftp_password} sftp://${ftp_host} ; put -O plugins/ target/vBungee.jar ; quit"
            curl "https://panel.benh.codes/api/client/servers/d66387f9/command" -H "Authorization: Bearer ${pterodactyl_api_key}" -H "Content-Type: application/json" -H "Accept: Application/vnd.pterodactyl.v1+json" -X POST -d '{ "command": "grestart 5m Network Maintenance" }'
